remote_theme: pmarsceill/just-the-docs
logo: images/openaf_medium.png
title: OpenAF docs
description: OpenAF guides, concepts and how-tos documentation.
eading_anchors: true
nav_sort: case_sensitive
collections:
  concepts:
    permalink: "/:collection/:path/"
    output: true
  howto:
    permalink: "/:collection/:path/"
    output: true
  guides:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    concepts:
      name: Concepts
    howto:
      name: How to
    guides:
      name: Guides