init:
  header: |
    ---
    layout: default
    title: {{title}}
    parent: {{pre}}
    grand_parent: Guides
    ---

jobs:
# ----------
- name: Init
  exec: |
    _$(args.pre, "pre").$_();
    global.pre = args.pre;

# ----------------
- name: Add header
  exec: |
    _$(args.file, "file").$_();
    _$(args.pre, "pre").$_();

    if (!String(args.file).endsWith(".md")) return;

    var f = io.readFileString(args.file);
    var title = f.match(/\# (.+)/)[1];

    var h = templify(global.args.init.header, { pre: args.pre, title: title });
    if (f.indexOf("---") != 0) {
      f = h + "\n" + f;
    } else {
      f = f.replace(/^---[^---]+---\n/mg, h);
    }
    io.writeFileString(args.file, f);

todo:
- name: Init
- name: Add header
  args: |
    io.listFiles(".").files.map(f => ({ file: f.canonicalPath, pre: global.pre }));